name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm run check-format
      - run: npm run build
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
